server:
  port: ${SERVER_PORT:8080}
management:
  health:
    binders:
      enabled: true
  endpoint:
    include: health,info,metrics,prometheus
spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  datasource:
    hikari:
      connection-timeout: 20000
      minimum-idle: 2
      maximum-pool-size: 20
      idle-timeout: 10000
      max-lifetime: 30000
      pool-name: moped_pool
      auto-commit: true
secret: 97CB86AFD221F8FA461297923C46B
validityInMinutes: 15
refresh:
  token:
    duration:
      minutes: 60